# Generated by Django 4.0.4 on 2022-05-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.CharField(max_length=50, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=50, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description_short', models.TextField(max_length=300, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('coordinates', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.coordinate', verbose_name='Координаты')),
            ],
        ),
    ]
