# Generated by Django 4.0.4 on 2022-05-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_description_short_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailsUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, max_length=500, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Полное описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.CharField(max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.CharField(max_length=50, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=50, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='place_properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='places.detailsurl', verbose_name='Относятся к'),
        ),
        migrations.AddField(
            model_name='image',
            name='place_properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='places.detailsurl', verbose_name='Относится к'),
        ),
        migrations.AddField(
            model_name='place',
            name='properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='places.detailsurl', verbose_name='Координаты'),
        ),
    ]
