# Generated by Django 4.0.4 on 2022-05-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_detailsurl_remove_image_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='places.detailsurl', verbose_name='Детальная информация'),
        ),
    ]
