# Generated by Django 4.0.4 on 2022-05-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_coordinate_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='place_properties',
            new_name='place_details',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='place_properties',
            new_name='place_details',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='properties',
            new_name='details',
        ),
    ]
