# Generated by Django 4.0.4 on 2022-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_place_properties_coordinates_place_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='lat',
            field=models.CharField(max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='details',
            name='lng',
            field=models.CharField(max_length=50, null=True, verbose_name='Долгота'),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
