# Generated by Django 4.0.4 on 2022-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_image_position_number_image_img_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'ordering': ['details_sort']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['img_sort']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_order',
        ),
        migrations.AddField(
            model_name='details',
            name='details_sort',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='details_sort'),
        ),
        migrations.AddField(
            model_name='image',
            name='img_sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок фоток'),
        ),
    ]
