# Generated by Django 4.0.4 on 2022-05-14 10:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_details_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
    ]
