# Generated by Django 4.0.4 on 2022-05-16 14:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_details_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['img_sort'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['places_sort'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='place_details',
        ),
        migrations.RemoveField(
            model_name='place',
            name='details',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='places.place', verbose_name='Относится к'),
        ),
        migrations.AddField(
            model_name='place',
            name='details_description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='details_description_short',
            field=models.TextField(blank=True, max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='details_lat',
            field=models.CharField(max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='details_lng',
            field=models.CharField(max_length=50, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='details_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='place',
            name='places_sort',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Положение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='places/image/', verbose_name='Фотографии'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
