# Generated by Django 4.0.4 on 2022-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='details_lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='details_lng',
        ),
        migrations.AlterField(
            model_name='place',
            name='details_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Полное название места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=50, null=True, verbose_name='Короткое название на английском'),
        ),
    ]
