# Generated by Django 3.2.13 on 2022-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_place_details_lat_remove_place_details_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Короткое уникальное название на английском'),
        ),
    ]
