# Generated by Django 3.2.13 on 2022-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_placeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/image/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_sort',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок фоток'),
        ),
        migrations.AlterField(
            model_name='place',
            name='places_sort',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Положение'),
        ),
    ]
