# Generated by Django 3.2.13 on 2022-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20220520_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(max_length=50, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Короткое уникальное название на английском'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
